version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: cubing-events-db
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test: [ "CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${SPRING_DATASOURCE_USERNAME}" ]
      timeout: 5s

  app:
    image: ghcr.io/ricky9667/cubing-tw-notifier:latest
    profiles: ["prod"]
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "false"

volumes:
  postgres_data:
